baseurl = "https://justinbarclay.ca"
title = "Justin Barclay"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

ignoreFiles = [ "literate_programming_against_rest_apis.org"]

paginate = 20

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true

[params]
  author = "Justin Barclay"
  info = "A software developer with an inflated sense of impostor syndrome"
  description = "They say time spent on this blog is definitely spent time"
  keywords = "blog,developer,personal"
  avatarurl = "images/portrait.jpg"
  since = 2017

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  customCSS = ["custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  # tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/justinbarclay/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 2
  rel = "me"
  url = "https://hachyderm.io/@newplagiarist"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  rel = "alternate"
  url = "/index.xml"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[markup]
[markup.goldmark.parser.attribute]
block = true
title = true
